### ISSUE TITLE
CWL CommandLineTools such as HaplotypeCaller include `analysis_type` input

### ISSUE THREAD

**Issue by jrandall** [yejinyou/PY#11]
There is an argument in the GATK json docs for `CommandLineTool` that specifies the `--analysis_type` (`-T`) which is the specific tool to invoke. 

The current gatk-cwl-generator generates CWL for specific tools that inclues an input called `analysis_type`. This makes no sense - if invoking HaplotypeCaller using the `HaplotypeCaller.cwl` CommandLineTool, there should be no option for what value to use for `-T` - it should be fixed as `HaplotypeCaller`.

**Comment by ThomasHickman** [comment]
This is fixed in version 2.0
