### ISSUE TITLE
short option versions don't show up anywhere in generated CWL

### ISSUE THREAD

**Issue by jrandall** [yejinyou/PY#19]
I would have expected the short versions of options (such as `-ERC` instead of `--emit-ref-confidence`) to appear somewhere in the CWL so that when looking for an option based on an example using the short version (which most of them do!), they can be found without having to refer back to the documentation manually.

**Comment by mr-c** [comment]
I guess it could be mentioned in the `doc` for the particular input?

**Comment by keysmashes** [comment]
Where there is a short option available, it's now added to the `doc` like so:

```yaml
- doc: Mode for emitting reference confidence scores [synonymous with -ERC]
```
