### ISSUE TITLE
Failing tests - wrong version of Python?

### ISSUE THREAD

**Issue by colin-nolan** [yejinyou/PY#3]
I had a go at running the test but unfortunately a couple fail, complaining:
```
TypeError: a bytes-like object is required, not 'str'
```

This screams of a Python 2 vs Python 3 issue. What version of Python is this tool designed for (it's not documented)? I assumed it would work on 3.6 but perhaps I'm wrong here!

**Comment by ThomasHickman** [comment]
Apart from running this tool with the option --dev (which uses requests_cache, which fails in python 3), this should work in both python 2 and 3. What's the full error message?

**Comment by ThomasHickman** [comment]
... also the tests don't work unless you have the cwl-example-data folder, which shouldn't be committed to git

**Comment by colin-nolan** [comment]
Yea, I was a bit confused about what data I needed there. Can I just add any set of valid `chr22_cwl_test.*` files? Do you know if there's any publically accessible files that could be used here?

**Comment by ThomasHickman** [comment]
Looks like it is a python 3 problem, as the tests work on python 2 but not python 3. Looking into fixing it now
